version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
